### ISSUE TITLE
Change focus step in pgcamera to be more readable

### ISSUE THREAD

**Issue by ckjellstrand** [PolarMesosphericClouds/PMC-Turbo#53]
Right now 0 -> 0 focus step, 1000 -> max focus step. This isn't useful for sending change focus commands. Look for a place where this information is sent to ground or allow it to be entered manually upon starting pgcamera.

**Comment by ckjellstrand** [comment]
Approximate focus step in there. Easy enough to make a command line argument but that seems annoying each time to start up. pgcamera looks at JPEGFiles while the max focus step is in ShortStatus messages, and I don't want pgcamera to be looking at ShortStatus messages unless we add a lot of features.

**Comment by gitj** [comment]
Does this work for wide and narrow field cameras?

On Sep 21, 2017 10:12 PM, "ckjellstrand" <notifications@github.com> wrote:

Approximate focus step in there. Easy enough to make a command line
argument but that seems annoying each time to start up. pgcamera looks at
JPEGFiles while the max focus step is in ShortStatus messages, and I don't
want pgcamera to be looking at ShortStatus messages unless we add a lot of
features.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/PolarMesosphericClouds/PMC-Turbo/issues/53#issuecomment-331331291>,
or mute the thread

**Comment by ckjellstrand** [comment]
Added for narrow field camera as well

**Comment by ckjellstrand** [comment]
Closed by 12cb1381af0369367a32bf77e8b1a6ad9755f742
